version: '3.8'
services:
    postgres:
        image: postgres:latest
        volumes:
            - postgres_data:postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER = user
            POSTGRES_PASSWORD = password
            POSTGRES_DB = mydatabase
        networks:
            - mynetwork

    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes:
      - ./backend:/app
      environment:
        DATABASE_URL: postgresql://user:password@postgres/mydatabase
      depends_on:
        - postgres
      networks:
        - mynetwork
    frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      volumes:
        - ./frontend:/app
      ports:
        - "8501:8501"
      networks:
        - mynetwork

networks:
    mynetwork:

volumes:
    postgres_data: