version: '3.8'
services:
    postgres:
        image: postgres:latest
        volumes:
            - /path/to/postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        networks:
            - mynetwork

    src:
      build: 
        context: ./src
        dockerfile: Dockerfile
      volumes:
        - ./src:/app
      ports:
        - "8502:8501"
      environment:
        DATABASE_URL: postgresql://user:password@postgres/mydatabase
      depends_on:
        - postgres
      networks:
        - mynetwork

networks:
    mynetwork:
